### PR TITLE
Remove the numeracy validation

### PR DESCRIPTION
**Pull request by Martin-Alexander**
This validation is almost completely redundant when we already have a validation to ensure that `rating` is an integer between 0 and 5.

In my experience it's also confusing for the students. And it's difficult for the teacher/TAs to explain why it's even necessary given the other validation.

Cc: @stephlaf

### CODE REVIEW

**Comment by stephlaf** [comment]
Agreed!

**Comment by dmilon** [comment]
Hi @Martin-Alexander @stephlaf :wave: Thank you for your contribution :pray: 

The `rating should be an integer` unit test checks that there is a `numericality: {only_integer: true}` validation [just like in the solution](https://github.com/lewagon/rails-yelp-mvp/blob/12429a238da949741b8264b97d6ac5335821a571/app/models/review.rb#L4) whereas the `rating should be a number between 0 and 5` uni test checks that there is a `inclusion: {in: 0..5}` validation. 

I agree that the `rating should be a number between 0 and 5` unit test current implementation actually checks that the rating is an integer to but it's not its purpose. 

From a TDD viewpoint, I think it's better to keep two separate unit tests if there are two different validations since unit tests are dev specs.

Instead of removing the `rating should be an integer` unit test, maybe we can make its purpose more explicit by adding `expect(Review.new(attributes.merge(rating: 2.5))).not_to be_valid` :thinking: 

WDYT?

**Comment by Martin-Alexander** [comment]
I don't really understand why we need a "numericality" validation in the first place. (I understand that the validation does have some differences in behaviour, but they are very subtle and difficult to explain to students).

Especially from the student's perspective. Like, when they ask me, "Why do I need a numericality validation if I already have inclusion?" and the best answer I (and other TAs) have is just "because that's what the tests want".

And these questions come up often because if they don't have the "numericality" validation then the `rating should be an integer` test case fails. On Wednesday, out of a batch of 16 I think I had 4 or 5 tickets regarding this issue.

**Comment by Martin-Alexander** [comment]
Errr, actually, I think I changed my mind.

The numericality validation makes it so that non integer attributes don't get automatically casted into integers, but rather cause validation errors. 

In that case, if the numericality validation should be kept in then I think that that should be explained in the instructions. Perhaps I'll open an issue

**Comment by dmilon** [comment]
Closed in favor of https://github.com/lewagon/fullstack-challenges-03-Rails-restaurant-reviews-specs/pull/8

**Comment by dmilon** [comment]
I've added a spec in the README to make it more explicit that we require an extra validation for the numericality: https://github.com/lewagon/fullstack-challenges/pull/2012

**Pull request closed without merging**
